# Generated by Django 4.1.3 on 2023-07-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bcc_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnumber', models.CharField(max_length=2)),
                ('leaders', models.CharField(max_length=100)),
                ('secretary', models.CharField(max_length=100)),
                ('pastoral_minstry', models.CharField(max_length=100)),
                ('education_minstry', models.CharField(max_length=100)),
                ('socialaction_minstry', models.CharField(max_length=100)),
                ('family_minstry', models.CharField(max_length=100)),
                ('laity_minstry', models.CharField(max_length=100)),
                ('youth_minstry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnumber', models.CharField(max_length=2)),
                ('family_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=400)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('unitnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.family')),
            ],
        ),
    ]
