# Generated by Django 4.1.3 on 2023-07-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='unitnumber',
            new_name='familynumber',
        ),
    ]
