# Generated by Django 4.1.3 on 2023-08-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parishcouncil',
            old_name='Desigination',
            new_name='desigination',
        ),
        migrations.RenameField(
            model_name='parishcouncil',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parishcouncil',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='parishpreist',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='parishpreist',
            old_name='Priestname',
            new_name='priestname',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='Phone',
            new_name='phone',
        ),
    ]
