# Generated by Django 4.1.3 on 2023-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_desigination_parishcouncil_desigination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='category',
            field=models.CharField(default='misc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
