# Generated by Django 4.1.3 on 2023-07-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_unitnumber_person_familynumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='family_number',
            new_name='familynumber',
        ),
    ]
