# Generated by Django 4.1.3 on 2023-08-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_phonenumbers_category_phonenumbers_designation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phonenumbers',
            new_name='phoneno',
        ),
    ]
