# Generated by Django 4.1.3 on 2023-07-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_family_number_family_familynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='unitnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bcc_unit'),
        ),
    ]
