# Generated by Django 4.1.3 on 2023-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_family_unitnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='familynumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
