# Generated by Django 4.1.3 on 2023-08-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='email',
        ),
    ]
