# Generated by Django 4.1.3 on 2023-07-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_family_familynumber_alter_family_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
