# Generated by Django 4.1.3 on 2023-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=100, max_length=10, null=True),
        ),
    ]
