# Generated by Django 4.1.3 on 2023-07-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
