# Generated by Django 4.1.3 on 2023-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
