# Generated by Django 4.1.3 on 2023-07-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_person_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bcc_unit',
            old_name='socialaction_minstry',
            new_name='social_action_minstry',
        ),
    ]
