# Generated by Django 4.1.3 on 2023-07-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_family_familynumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={},
        ),
        migrations.AlterField(
            model_name='family',
            name='familynumber',
            field=models.IntegerField(max_length=100),
        ),
    ]
