# Generated by Django 4.1.3 on 2023-07-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_family_options_alter_family_familynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='familynumber',
            field=models.IntegerField(),
        ),
    ]
