# Generated by Django 4.1.3 on 2023-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_family_familynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
