# Generated by Django 4.1.3 on 2023-07-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcc_unit',
            name='unitname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
