# Generated by Django 4.1.3 on 2023-07-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_bcc_unit_unitname'),
    ]

    operations = [
        migrations.CreateModel(
            name='parishpreist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priestname', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
